import { removeEmpties } from "../src/parse-xlsx"

/* eslint-disable no-undef */
const table = [
  [
      "",
      "PREHEADER _TEXT",
      "PREHEADER _ANCHOR",
      "",
      "TEXT_TITLE",
      "TEXT_DESCRIPTION",
      "TEXT_ORDER CHECK",
      "TEXT ORDER CHECK ANCHOR FIRST",
      "TEXT ORDER CHECK ANCHOR SECOND",
      "",
      "RETURN_TEXT-FIRST",
      "RETURN_TEXT-SECOND",
      "RETURN_TEXT-THIRD",
      "",
      "CTA_FIRST_TEXT",
      "CTA_SECOND_TEXT-FIRST",
      "CTA_SECOND_TEXT-SECOND",
      "CTA_SECOND_TEXT-THIRD",
      "",
      "FOOTER_FIRST_ANCHOR-FIRST",
      "FOOTER_FIRST_ANCHOR-SECOND",
      "FOOTER_FIRST_ANCHOR-THIRD",
      "FOOTER SECOND ANCHOR FIRST",
      "FOOTER SECOND ANCHOR SECOND",
      "FOOTER_THIRD_TEXT",
      "FOOTER_THIRD_ANCHOR"
  ],
  [
      "ita",
      "Se non riesci a visualizzare il contenuto di questa email",
      "clicca qui",
      "",
      "GRAZIE PER ESSERTI REGISTRATO",
      "Gentile [Name F/M],\r\nti diamo il benvenuto nel nostro negozio online. \r\n\r\nDa questo momento puoi approfittare dei vantaggi a te dedicati!",
      "Puoi modificare in qualsiasi momento i dati della tua registrazione nell'area Il tuo Account.",
      "Il tuo Account",
      "",
      "",
      "SALVA I TUOI ARTICOLI PREFERITI",
      "CONCLUDI GLI ACQUISTI PIÙ VELOCEMENTE ",
      "SEGUI LA SPEDIZIONE DI ORDINI E RESI",
      "",
      "INIZIA LO SHOPPING",
      "DONNA",
      "UOMO ",
      "BAMBINO",
      "",
      "INFO SULLA SPEDIZIONE",
      "FAQ",
      "RESI E CAMBI",
      "Area legale",
      "Privacy policy",
      "Se non riesci a visualizzare il contenuto di questa email",
      "clicca qui"
  ],
  [
      "en",
      "If you cannot see the content of this email",
      "click here",
      "",
      "THANK YOU FOR REGISTERING",
      "Dear [Name F/M],\r\nwelcome to our online store. \r\n\r\nWe are delighted to share with you our specially selected perks.",
      "You can change your registration details at any time in the Your Account section.",
      "Your Account",
      "",
      "",
      "SAVE YOUR FAVOURITE PRODUCTS",
      "MAKE YOUR PURCHASES EASIER",
      "TRACK YOUR ORDER  AND RETURNS",
      "",
      "START SHOPPING",
      "WOMEN",
      "MEN ",
      "KIDS",
      "",
      "SHIPPING INFO",
      "FAQs",
      "RETURNS AND EXCHANGES",
      "Legal section",
      "Privacy policy",
      "If you cannot see the content of this email",
      "click here"
  ],
  [
      "en_uk",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      ""
  ],
  [
      "de",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      ""
  ],
  [
      "es",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      ""
  ],
  [
      "fr",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      ""
  ],
  [
      "jp",
      "このメールが正しく表示されない場合は",
      "こちらをクリックしてください",
      "",
      "ご登録いただきありがとうございます",
      "[名前 F/M]様\r\nオンラインストアへようこそ。 \r\n\r\n今後、ご登録者限定の特典をお楽しみただけます！",
      "ご登録内容はマイアカウントからいつでも変更できます。 ",
      "マイアカウント",
      "",
      "",
      "お気に入りのアイテムを保存する",
      "より早く購入できます ",
      "オーダーの配送と返品状況を確認する",
      "",
      "ショッピングを開始する",
      "レディース",
      "メンズ ",
      "キッズ",
      "",
      "配送状況",
      "よくある質問",
      "返品および交換",
      "法的情報",
      "プライバシーポリシー",
      "このメールが正しく表示されない場合は",
      "こちらをクリックしてください"
  ],
  [
      "kr",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      ""
  ]
]

test("Testing horizintal table style to json", () => {
  const out = removeEmpties(table)
  console.log(out[0])
})
